### ISSUE TITLE
PublisherConsents object doesn't match spec

### ISSUE THREAD

**Issue by nhagen** [appnexus/cmp#108]
The `publisherConsents` object returned by the CMP is missing the `Consents` suffix on `standardPurposes` and `customPurposes`, which would make them `standardPurposeConsents` and `customPurposeConsents` per the spec (copied below):

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md#publisherconsents

```
{  
  metadata: ...
  gdprApplies:  *Boolean*,
  hasGlobalScope: *Boolean,*
  standardPurposeConsents: {
    *purposeId*: *consentBoolean*,
    ?
  },
  customPurposeConsents: {
    *customPurposeId*: *consentBoolean*,
    ?
  }
}
```

**Comment by krishoyt** [comment]
Thanks for catching that. Updated here: https://github.com/appnexus/cmp/pull/111
