### ISSUE TITLE
isLoaded callback

### ISSUE THREAD

**Issue by binoculars88** [appnexus/cmp#122]
Hi,

The ad network I'm working with provided me with a js tag which auto fires a version of this CMP.
I want to change it a bit, and am possible to do (for example as a test):
```
        setTimeout(function(){
            window.__cmp('ping', null, function(result) {
                console.log('ping callback result: ' + JSON.stringify(result, null, 2));
            });
        }, 5000);
```

This works, but obviously I don't want to "guess" whenever the cmp is loaded. How can I detect when I can start using `window.__cmp` without getting: "window.__cmp is not defined" ?

**Comment by krishoyt** [comment]
The CMP should be included as one of the first things on the page with a stub function something like this: https://github.com/appnexus/cmp/blob/master/src/docs/lib/stub.js.  So you should not have to worry about `window._cmp` being undefined.  Commands you call before the actual script is loaded from the server will be queued and called when the CMP implementation is ready. 

You can call `window.__cmp('getConsentData', null, callback)` and expect your callback to be executed when the CMP is ready (the spec dictates that the callback will not be called if there is no consent data so make sure to timeout after a short period).
