### ISSUE TITLE
TCF 2 ?

### ISSUE THREAD

**Issue by cwbeck** [appnexus/cmp#137]
Is this project going to be updated to support TCF 2?

**Comment by alanStocco** [comment]
I'm interested too.

**Comment by krishoyt** [comment]
There are no plans to update this project to support TCF 2.  This was created as an example CMP implementation and not as a product that will be supported or maintained.

**Comment by giegi** [comment]
I have also interest in the mantainance and the support of this project to the 2.0 tcf 
As krishoyt wrote, it seems there is no plan to support it.
I'm sure I'll have the need to do this update. 
If someone is interested, we could create a working group to mantain this product up to date.

**Comment by alanStocco** [comment]
I think I'll move to other solution for the main core anyway I'll glad to collaborate in free time also in order to improve my skills in React.
Only problem I hate to read/understand the tons of specifications written vaguely which IAB will surely give for TFC 2 :D
