### ISSUE TITLE
IAB Vendor List

### ISSUE THREAD

**Issue by cwbeck** [appnexus/cmp#25]
Hi,

How can we use this to support and reference the IAB Vendor List (https://vendorlist.consensu.org/vendorlist.json)

Thanks,

Chris

**Comment by krishoyt** [comment]
I don't think there is an agreed upon way to request this master list yet.  I have added the latest copy of it to this project, but for now you would have to host it yourself.

**Comment by cwbeck** [comment]
@krishoyt, thanks for the update. I'll check it out

**Comment by krishoyt** [comment]
CORS headers have been added and the code has been updated to request the IAB list directly.
