### ISSUE TITLE
z-Index issue on overlay

### ISSUE THREAD

**Issue by cwbeck** [appnexus/cmp#39]
The z-index needs to be set to max for the CMP

![screen shot 2018-05-01 at 11 40 17](https://user-images.githubusercontent.com/425262/39470348-1279f3e6-4d35-11e8-9a5a-599fd144f4f5.png)

**Comment by krishoyt** [comment]
It's set really high already.  I think if a site was using this script and had a need to set it higher they could just override the style.  I'm not sure what an appropriate "max" would be for all situations.  The UI pictured above is merged into master now if you want to modify it.
