### ISSUE TITLE
changing publisher purposes version does not affect cmp show

### ISSUE THREAD

**Issue by sss13579** [appnexus/cmp#40]
Seems consent tool should be shown when version in purposes.json changed as standard behavior.

**Comment by krishoyt** [comment]
Sounds like you are referring to the behavior when including `cmp.complete.bundle.js`?  That include was meant as an example to show you how you _could_ implement the logic.  If you are going to use this CMP you should configure the script outlined on the Setup page.  I'll update the docs to make this more clear.
