### ISSUE TITLE
Banner version

### ISSUE THREAD

**Issue by lgiraudel** [appnexus/cmp#41]
Hello,

When I go to your documentation and [show the consent tool](http://acdn.origin.appnexus.net/cmp/docs/#/basic/show), I have the banner version but when I try the same thing with local sources from master branch, I still have the modal version.

Is this banner version a custom branch not merged to master yet? Or is this a customized version dedicated to AppNexus and not available in github?

Thanks for your help.

**Comment by krishoyt** [comment]
That is just another version that we are trying.  I will probably merge that into github soon.
