### ISSUE TITLE
storeConsentGlobally: true - is not handling Safari failures (when 3'rd party cookies can't be set)

### ISSUE THREAD

**Issue by sam14432** [appnexus/cmp#42]
If I use this config setting:

storeConsentGlobally: true

..on Safari, there is no fallback to use a 1'st party cookie when writing of the 3'rd party cookie fails.

The effect is that the popup-window appears on every page load for Safari users - as the 3'rd party cookie is never written.

Would it be possible to implement this so that other browsers can still use global consent but Safari users will fallback to local consent?

**Comment by krishoyt** [comment]
Sounds like you are referring to the behavior when including `cmp.complete.bundle.js`?  That include was meant as an example to show you how you _could_ implement the logic.  If you are going to use this CMP you should configure the script outlined on the Setup page.  I'll update the docs to make this more clear.

**Comment by ferranbonas** [comment]
We've got the same problem with Safari on iOS. We are using the script on the Setup page, but there is no fallback. Any ideas to switch the storeConsentGlobally to false when that occurs? Thanks

**Comment by Broutard** [comment]
You only have to detect safari on your stub and use it in your storeConsentGlobally config

**Comment by sam14432** [comment]
..more exactly (as this problem also occurs for users who disable 3'rd party cookies in the other browsers) - I think the solution should be something like the code in portal.html check if document.cooke changed after updating it, and then indicate if the cookie-setting was successful in the response back. 

So there must be some check on the 3'rd party domain I believe.
