### ISSUE TITLE
Master disable switch does not propagate to rest of list...

### ISSUE THREAD

**Issue by cwbeck** [appnexus/cmp#54]
Master disable switch does not propagate to rest of list...

@master branch commit **fdaddd7ab4ca144cb8415d3b7b5e4f2f9c0f9828**

![screen shot 2018-05-16 at 10 29 10](https://user-images.githubusercontent.com/425262/40108916-263d02b8-58f4-11e8-8c30-ccbda6397325.png)

![screen shot 2018-05-16 at 10 29 17](https://user-images.githubusercontent.com/425262/40108933-2eab4bc6-58f4-11e8-9580-d3ad4ddde503.png)

**Comment by krishoyt** [comment]
These switches were always changing separate things and were not connected.  The "Inactive" switch was just changing the consent for the "purpose". While the switches on the "Our partners" page were setting consent for the "vendor".  

I've just merged a new UI that looks totally different.  Switches in this new UI currently only set consents for vendors.
