### ISSUE TITLE
showConsentTool & the new banner

### ISSUE THREAD

**Issue by Broutard** [appnexus/cmp#57]
With the yesterday last changes, `showConsentTool` opens the new banner... not the consent popup :(

Is there a new way to open the popup ?

Maybe the parameter may takes 'popup' or 'banner' ...

**Comment by krishoyt** [comment]
Nah, that's the workflow we have now.  You'd have to modify the code to trigger the modal directly if you want.

**Comment by SucheG** [comment]
@Broutard Please do you have some solution for that ? I can't edit source code :/

**Comment by Broutard** [comment]
personally, I added a showConsentBanner method

**Comment by SucheG** [comment]
Oh, thanks. Some implementation details please ?
It  would help me a lot.

**Comment by Broutard** [comment]
`src/lib/cmp.js`

```
               /**
		 * Trigger the consent tool UI to be shown (banner)
		 */
		showConsentBanner: (show = true, callback = () => {}) => {
			this.store.toggleConsentToolShowing(show);
			callback(show);
		},

		/**
		 * Trigger the consent tool UI to be shown (popup)
		 */
		showConsentTool: (show = true, callback = () => {}) => {
			this.store.toggleModalShowing(show);
			callback(show);
		},
```

**Comment by SucheG** [comment]
Thank you, works very well.
I know only the plain JS, this source code is written in React ?

**Comment by BartVB** [comment]
Something like this has been included in the CMP:
https://github.com/appnexus/cmp/issues/93#issuecomment-401135484

Use:

`__cmp('showModal');`
to invoke the modal with the choices.

This is not a modal with the more general 'we are using cookies; accept all' message though.
