### ISSUE TITLE
Show Consent Tool only if consent not yet given

### ISSUE THREAD

**Issue by vajkri** [appnexus/cmp#58]
Hi, how do I check for whether consent has been given? Because once it has, the consent tool shouldn't be shown anymore to users.

I tried using 
```
__cmp('getConsentData', null, function(result) {
  if(!result) {
    __cmp('showConsentTool');
  }
});
```
for this, but the callback is only run, if consent has been given already. So I cannot really use this to check whether it is or not.

**Comment by Broutard** [comment]
+1 
The `cmp.processCommand` method check if data is available. If not, it queue the `getConsentData` command :(

**Comment by mahammer** [comment]
This works already. The thing is, if you use `cmp.bundle.js` it will not even trigger automatically.
If you use `cmp.complete.bundle.js` it will check multiple things, just like the /docs say:

/docs/#/quickstart
> Determine if the consent tool should be shown to the user:
> If cookies are disabled: do nothing
> If consent data exists and the vendor list version is current: do nothing
> If no consent data is found: show the consent tool
> If consent data is found and the vendor list version does not match: show the consent tool

One thing that's weird though is, if you use a publisherVendorList in your `.well-known` it replaces the vendorlist version with 0, breaking the checking for version differences and running the tool again on changes.

Also indirectly into this plays what Broutard tries, the cmp should emit an event if consent information was found so publishers can trigger actions on an impression that has information available already and will not start the cmp and emit `onSubmit`

**Comment by Broutard** [comment]
The doc say that `cmp.complete.bundle.js` should NOT be used on an actual site.
So how to do the same with the recommended method /docs/#/setup ?

**Comment by Broutard** [comment]
@mahammer 

> You have to properly declare the cmp's stub first queuing calls
what's in your stub script ?

For me `cmp.complete.bundle.js` already contains it.

>

**Comment by krishoyt** [comment]
You should NOT use `cmp.complete.bundle.js` for anything other than testing.  You should include the stub which will load `cmp.bundle.js`.

@Broutard You should implement your own logic _like_ `checkConsent` that you referenced above.  That was just my example of some checks you could do to determine if you want to request consent.  Your requirements may be different.

**Comment by mahammer** [comment]
So this means if we use `cmp.bundle.js` nothing works automatically and all we can do:

1) check if cookies are disabled, do nothing.
2) check if the `euconsent` cookie is present or if the `getVendorConsent` return is `'undefined'`, if not launch the cmp
3) if `euconsent` is present, request the vendorList and the vendorConsents and compare versions, if missmatch, launch the cmp, else do nothing

@2 do I see it correctly that the result of the call to `__cmp('getVendorConsents')` returns `'undefined'` if no consent cookie is available, no matter if the cmp is loaded or not?

**Comment by krishoyt** [comment]
`cmp.bundle.js` loads everything needed to be able to interact with the CMP, but doesn't trigger asking for consent automatically.  You should implement whatever logic you deem necessary for your site before asking for consent.  You may want to check the Geo, check other cookies, determine consent has expired, etc.  Those things will differ between sites and are not the responsibility of the CMP.

You never have to check the cookie yourself. `getVendorConsents` and `getConsentData` reflect what is in the cookie.  These functions will never return `undefined`.  If there is no consent information in the cookie the commands will be queued until consent information has been persisted and then will execute their callbacks.

**Comment by mahammer** [comment]
They "return" 'undefined' for me or at least it's undefined in the callback if it's queued. And it seems the only way to really check if you initially need to show the cmp:

```
window.__cmp('addEventListener', 'cmpReady', function(){
  window.__cmp('getVendorConsents', null, function(consentCookie){
    if (typeof(consentCookie) === 'undefined') {
      console.log("No GDPR consent cookie found. Starting CMP...");
      window.__cmp('showConsentTool');
    } else {
      console.log("GDPR consent cookie found.");
    }
});

**Comment by krishoyt** [comment]
If you mean the return value from the `window.__cmp` function call, then yes it is `undefined` and will always be.  I meant that the value provided to the callback will never be undefined.

I don't like that a call to `getVendorConsents` doesn't return until consent data is present, but that's how the v1.1 spec defines it so I changed it to work that way.  Since you know when the CMP is loaded you can set a short timeout and if you don't get a callback from `getVendorConsents` assume there is no consent data.

You could look at the cookie, but that's only gonna work if it's stored on the first-party domain.

**Comment by vajkri** [comment]
@krishoyt I understand it is the implementer's responsibility to code what we need, but it'd be really helpful with some common use case examples. Like how to only trigger showConsentTool if not already given consent. Can you help with this?
