### ISSUE TITLE
New UI & customPurposes

### ISSUE THREAD

**Issue by Broutard** [appnexus/cmp#59]
It seems custom purposes are not displayed anymore in the new UI.
Right ?

purposes.json
```
{
  "version": 1,
  "purposes": [
	{
	  "id": 1,
	  "name": "Custom Purpose 1",
      "description": "Lorem ipsum dolor..."
	},
	{
	  "id": 2,
	  "name": "Custom Purpose 2"
	}
  ]
}
```

config
```
{
                customPurposeListLocation: '/.well-known/purposes.json',
                storePublisherData: true,
                logging: 'debug',             
            }
```

**Comment by cwbeck** [comment]
@krishoyt I have to ask... what is the logic behind not showing this to the user? How are they supposed to see it and agree to it? This seems completely counter-intuitive to me.

@Broutard what did you end up doing to handle this?
