### ISSUE TITLE
Global cookie with custom vendorlists

### ISSUE THREAD

**Issue by saraneus** [appnexus/cmp#61]
Hi, we want to use CMP for a network of websites of our clients, so I set up global cookie. Every client has it's own vendorlist defined where the version is increased every time the client makes changes to it. I set up CMP to use global cookie:

`cmp.config = {
     globalVendorListLocation:"https://vendorlist.consensu.org/vendorlist.json",
     globalConsentLocation: 'http://cookie-domain.abc/portal.html',
     storeConsentGlobally: true,
}
`
For each client the CMP tool is compiled with the client's individual vendor list, I set PUB_VENDOR_LOCATION in vendor.js to fetch the vendor list from the client's domain.

If a user opens a website the first time, the CMP displays the dialog. If the user confirms and opens another website, with different vendors defined the dialog isn't displayed. It should be displayed if there are vendors defined the user has never agreed to.

I'm not sure if this is a bug or intent behaviour.  I appreciate any comment on this.

**Comment by krishoyt** [comment]
All of the logic to determine if you want to show the consent tool should be implemented by you.  See this discussion: https://github.com/appnexus/cmp/issues/58
