### ISSUE TITLE
getPublisherConsents and getVendorConsents return the same metadata

### ISSUE THREAD

**Issue by dmitriyshashkin** [appnexus/cmp#64]
According to the specification: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md

1) getPublisherConsents calls callback function with PublisherConsents as the parameter. PublisherConsents.metadata should contain "encoded string in the publisher consent format"

2) getVendorConsents calls callback function with VendorConsents as the parameter. VendorConsents.metadata should contain "string (header data from the vendor consent format, as described below)"

As I understand "publisher consent format" and "vendor consent format" are different formats. Yet when I clone the latest version of appnexus/cmp and run yarn start, go through consent dialog and then call cmp api:

```
window.__cmp('getVendorConsents', null, function(d){console.log('concent cb', d.metadata)})
window.__cmp('getPublisherConsents', null, function(d){console.log('concent cb', d.metadata)})
```

In both cases I get the same result:
`concent cb BOOM_WVOOM_WVABABAENAZ-AAAARF7______b933__7v9uD7Kr_K7VfxnHGUr2hPVA9LDOAqAAQ`

Am I missing something?

**Comment by krishoyt** [comment]
You are correct, they both contain the vendor consent string.  I'll have to update the publisher consent string.
