### ISSUE TITLE
use https connection

### ISSUE THREAD

**Issue by lucop1** [appnexus/cmp#65]
hello is there a way to set up the script in order to use ssl certificates?

actually it runs only on http connection

**Comment by Broutard** [comment]
No problem for me over https

**Comment by lucop1** [comment]
the tool uses node to build then if I access the the URL and the port 5000 with https the certificate is not issue and not valid since the machine is running on node.

**Comment by Broutard** [comment]
It is not an app issue, you can build and use another webserver to handle SSL.

Maybe you can use https://www.npmjs.com/package/serve-https

**Comment by dmitriyshashkin** [comment]
You're not supposed to use node server in production. It's for testing purposes only. Run yarn build, get the file from "build" folder and serve it like a regular static file using your web server of choice.

**Comment by lucop1** [comment]
@dmitriyshashkin that's what I was thinking! thank you!
