### ISSUE TITLE
design not responsive

### ISSUE THREAD

**Issue by lucop1** [appnexus/cmp#66]
Hello, from mobile device the banner and also the popup doesn't show up correctly, everything seems cropped.

**Comment by Broutard** [comment]
see PR62

**Comment by lucop1** [comment]
@Broutard yeah I saw but unfortunately is not compatible with translations included in the latest release. I'll try to fork and update it.

**Comment by krishoyt** [comment]
This was addressed by https://github.com/appnexus/cmp/pull/102.
