### ISSUE TITLE
How is encapsulation handled in this application?

### ISSUE THREAD

**Issue by ydennisy** [appnexus/cmp#68]
Hello,
Since this app is bundled and injected into various third party / host websites - how do you ensure that CSS, JS etc remains non polluted both ways?
Thanks!
Dennis

**Comment by krishoyt** [comment]
The only JS that is added to the global namespace is the `__cmp` function.  All CSS is scoped to the CMP UI components with randomly generated class names so rules should not apply to anything outside those components.  However, CSS in a page could have rules that will affect the CMP.  You may need to adjust your CSS or the CMP components to make sure things render correctly.

**Comment by ydennisy** [comment]
@krishoyt is it not possible to load the whole app into an iFrame?
