### ISSUE TITLE
Are custom purposes being loaded? 

### ISSUE THREAD

**Issue by dashiad** [appnexus/cmp#73]
The index.html file generated by the "build" command, includes this configuration:
`cmp.config = {
					customPurposeListLocation: 'docs/purposes.json',
					globalConsentLocation: 'docs/portal.html'
				};`
I cant see the docs/purposes.json file being loaded in the browser (so nothing is shown in the UI).
Is anything else needed to load the Custom Purpose list?

**Comment by krishoyt** [comment]
The custom purposes do not render anywhere in the current UI.  They still get pulled in if they exist, but you would have to render them yourself.
