### ISSUE TITLE
Allow/Reject all button issue

### ISSUE THREAD

**Issue by Broutard** [appnexus/cmp#77]
If I reject all vendors in a purpose that doesn't contain them all, they are all rejected.

Step to reproduce :
- go to purpose "Personalisation" (2)
- double click "accept all" to reject all vendors in this purpose

=> getVendorConsents returns false for each vendors (even vendor 12 which is not in this purpose).

```
handleAcceptAll = () => {
	this.props.selectAllVendors(true);
};

handleRejectAll = () => {
	this.props.selectAllVendors(false);
};
```
seems to be not relative to purpose.

**Comment by krishoyt** [comment]
Yeah, purpose consent isn't actually stored per vendor so I never bothered to limit this.  If this is causing an issue for you somewhere please submit a PR.

**Comment by rupl** [comment]
I've also noticed that the text "Allow all" doesn't change once clicked, even though the functionality does. Although the text never changes, clicking it twice will deselect all.

**Comment by krishoyt** [comment]
These issues were addressed by: https://github.com/appnexus/cmp/pull/118
