### ISSUE TITLE
CMP UI not showing automatically

### ISSUE THREAD

**Issue by dashiad** [appnexus/cmp#79]
The API specs for the getVendorConsents, getConsentData and getPublisherConsents specifies that "The callback is called only after consent is obtained  from the UI or existing cookies".
But it doesnt include any method to show the UI "manually", so looks like showing or not the UI, is the CMP responsability.
This is something i find very difficult (there are many possible scenarios), so i don't really mind breaking the specs about this. But, if it's _my_ responsability to show the UI, i'd need to get more information from the CMP (like if the user already has a cookie or not), specially if using global cookies.
I've seen in other issues some patches to the CMP code to bring back the "autoshow" functionality, but if the showConsentTool is part of the API, it's because it should be called from user code, so i'd prefer to also keep the show-or-not logic in user code.
Are there plans to add additional commands to the API to know if the cookie exists or not?

**Comment by krishoyt** [comment]
If you know the CMP is ready then you can call `getConsentData` and if your callback isn't called in a few milliseconds you know that there is no cookie data.  

I don't know of any plans to add additional functions that return this data, but future versions may change so the callbacks are called immediately instead of waiting for some consent data to exist.  I would personally rather have the callbacks called immediately with no arguments if there is no consent data available.

**Comment by dashiad** [comment]
Having the CMP loaded is required for many functionalities on the page, including ads. And loading the CMP js, vendorlist.json, pubvendors.json, and possibly other dependencies if global consent is enabled, have already taken a few milliseconds..Adding more milliseconds there for a timeout to expire, in that moment of the page load process, is not something i'd be very happy about.
I think the API functions signature is right for the most cases. In my opinion, the problem is in the event semantics. 
I cant see the usefulness of  the "isLoaded" and "cmpReady" events for the user code, specially when the difference is that vendorlist is loaded or not.That's useful for the CMP, not for the usercode. The user code doesnt depend on the vendorlist.json to be loaded or not...Depends on having consent information available, but there's no event for that.
