### ISSUE TITLE
vendorListVersion set to 0 when using publisher vendor list

### ISSUE THREAD

**Issue by kosik86** [appnexus/cmp#81]
When the publisher list is loaded the CMP always sets the `vendorListVersion` to 0 and it seems that there's no way to determine if there were any changes to the list.

https://github.com/appnexus/cmp/blob/master/src/lib/store.js#L359-L361
```
// If a pubVendorList is applied make the vendor list version = 0
const { publisherVendorsVersion } = pubVendorsList;
vendorList.vendorListVersion = publisherVendorsVersion ? 0 : vendorList.vendorListVersion;
```

is this expected behaviour? 
If the version is always stored as 0 how to decide when to show the consent tool after some changes have been made to the list?

**Comment by krishoyt** [comment]
We were using this to indicate that the publisher was using a custom list instead of the global.  I can't find this as a requirement anywhere so I'll change it back.

**Comment by krishoyt** [comment]
Updated: https://github.com/appnexus/cmp/pull/82

**Comment by kosik86** [comment]
@krishoyt this seems working, but shouldn't it keep track of publisher vendor list?
I was thinking of storing the `vendorListVersion` as a combination of publisher list version and global list version, e.g. `10.53` if global is 53 and publisher is version 10.
So if any of these lists change the CMP can determine that the cookie is outdated,
Would it work?

**Comment by krishoyt** [comment]
You can modify it to store data that way, but I'm not going to change anything here until it is added to the CMP specs put out by the IAB: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework
