### ISSUE TITLE
Issues with setting HTTP Cookies

### ISSUE THREAD

**Issue by ydennisy** [appnexus/cmp#83]
Does the framework have any suggestions/best practice/code snippets to show how third party cookies should be set in an ideal world?

The implementation I am working on is having issues cross browser.

Loading a CMP via a script tag on a publisher/advertiser site works well. As does then setting cookies from that domain.

However then making calls to the server to solicit a Set-Cookie header, does not seem to stick with all browsers.

Some help would be great, as cookies had been decided by the IAB as the storage mechanism, so guidance would be useful.

Thanks,
D

**Comment by kosik86** [comment]
You can load an iframe and use postMessage and listeners to communicate with your script loaded on another domain, see here: https://github.com/appnexus/cmp/blob/master/src/docs/assets/portal.js

It doesn't require a server-side solution, but 3rd party cookies won't work in some browsers (mainly Safari).

**Comment by krishoyt** [comment]
You will need to use iframes and postMessage to communicate with other domains.  The docs have examples of how to do this.

There will still be browser limitations as @kosik86 mentioned.
