### ISSUE TITLE
Possible to trigger Accept button (using the api not jquery) using API

### ISSUE THREAD

**Issue by rigids** [appnexus/cmp#91]
Is there a way to trigger accept/ok -continue to website button from the javascript using API?

Use case scenario would be for eg User clicks someother link which is within post/page content leading to accepting Site policies

**Comment by krishoyt** [comment]
Currently there is no function exposed for you to call to do that.  You would want to modify the code to show your different UI and then you need to call `persist` in https://github.com/appnexus/cmp/blob/master/src/lib/store.js to write the consent data to the cookie.
