### ISSUE TITLE
Is it possible to accept the Consent form on scroll of website

### ISSUE THREAD

**Issue by amorouscreations** [appnexus/cmp#92]
I am looking to find a way to accept the Consent form on scroll of website. is it possible?

**Comment by krishoyt** [comment]
It's not built to do that, but it should be pretty easy to modify things to do that.  You would need to expose the `persist` function in https://github.com/appnexus/cmp/blob/master/src/lib/store.js and trigger it when the page is scrolled.

**Comment by alanStocco** [comment]
A question: I need this change too because seems that in Italy for now is law accepted that a scroll mean accept. 
So can have sense introduce a config for this like acceptScroll true false  and commit or not?
Otherwise no prob I'll do for my own only. Thanks.
