### ISSUE TITLE
Giving consent to purposes

### ISSUE THREAD

**Issue by LukaszSawicki** [appnexus/cmp#94]
Hello,
Why in the new popup there is no possibility to save consent to purposes? On each purpose detail I can only accept vendors from the list, and in saved cookie all of the purposes have value 'false'. In previous version each purpose had his own field to give an consent.

**Comment by krishoyt** [comment]
Our latest UI design omitted this functionality.  I don't know when an update to that might come.

If you modify the code you can call `selectPurpose` on the store (/src/lib/store.js) and they will be persisted correctly as before.
