### ISSUE TITLE
Clarification: policyUrl format

### ISSUE THREAD

**Issue by rupl** [appnexus/cmp#96]
I notice in the global vendor list that Oracle/AddThis has an invalid `policyUrl` (it's two URLs comma separated). Since they are the only ones I assume this is an error that needs to be fixed. I found what appears to be a [spec for policyUrl](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/Consent%20string%20and%20vendor%20list%20formats%20v1.1%20Final.md) but it contains markdown which no vendor in the global list is actually using.

So I guess my question is to @krishoyt — how do we submit fixes to the global list? Or failing that, would you be open to a PR which makes URL handling more robust within the CMP?

**Comment by krishoyt** [comment]
Ah, I hadn't noticed that. I can't find it spelled out explicitly what the format should be and the spec example being markdown vs. what's actually in the vendor list makes it even more confusing.  Contacting someone at consensu.org would probably be the best way to get this updated.

I don't think we should add any URL parsing here until we know what is expected.  Closing for now.

**Comment by rupl** [comment]
Thanks for the response I will try to contact them and resolve it at the source.
