### ISSUE TITLE
Missing translations in Spanish

### ISSUE THREAD

**Issue by rafamarquezv** [appnexus/cmp#97]
Hi, 

The following translations entries are empty in Spanish (es):

- es.banner.links.data.title
- es.banner.links.data.description
- es.banner.links.purposes.title
- es.banner.links.purposes.description

Are there any official translations in Spanish for mentioned entries?

Thank you

**Comment by rafamarquezv** [comment]
Hi, I've already created a PR with the changes here: https://github.com/appnexus/cmp/pull/98

**Comment by krishoyt** [comment]
Merged
